### ISSUE TITLE
Error on line 3868

### ISSUE THREAD

**Issue by muralikodali** [Fitus/Zaloha2.sh#2]
I am using zaloha.sh for a long time.
i have replaced it zaloha2.sh and tried to sync my partition drive of 50GB to backup directory.

it exited with following error :  
```
Zaloha2.sh --sourceDir=/media/murali/tango/ --backupDir=/media/murali/hibiscus/tango/ --metaDir=/media/murali/hibiscus/Zaloha/tangobackup --findGeneralOps=  --findSourceOps='( -type d -a -name .Waste ) -prune -o' --mawk --noRestore
```

ANALYZING /media/xxxx/tango/ AND /media/murali/hibiscus/tango/

===========================================

    Parsing .............................................. done.
    exec find /media/murali/hibiscus/Zaloha/tangobackup/ -path /media/murali/hibiscus/Zaloha/tangobackup/999_mark_executed -type f -printf '///\tL\t%y\t%s\t%Ts\t%F\t%D\t%i\t%n\t%u\t%g\t%m\t0\t%P\t///' '(' -lname '*///*' -printf '\t' -o -printf '\t%l' ')' -printf '\t///\n'
    exec find /media/murali/tango/ '(' -type d -a -name .Waste ')' -prune -o '(' -lname '*///*' -printf '///\tSLINK-TARGET\t' -exec bash /media/murali/hibiscus/Zaloha/tangobackup/205_read_slink.sh '{}' ';' -printf '\t///\n' -false ')' -o -printf '///\tS\t%y\t%s\t%Ts\t%F\t%D\t%i\t%n\t%u\t%g\t%m\t0\t%P\t///' '(' -lname '*///*' -printf '\t' -o -printf '\t%l' ')' -printf '\t///\n'
    exec find /media/murali/hibiscus/tango/ '(' -lname '*///*' -printf '///\tSLINK-TARGET\t' -exec bash /media/murali/hibiscus/Zaloha/tangobackup/205_read_slink.sh '{}' ';' -printf '\t///\n' -false ')' -o -printf '///\tB\t%y\t%s\t%Ts\t%F\t%D\t%i\t%n\t%u\t%g\t%m\t0\t%P\t///' '(' -lname '*///*' -printf '\t' -o -printf '\t%l' ')' -printf '\t///\n'
    Cleaning ............................................. done.
    Checking ............................................. done.
    Sorting (2) .......................................... done.
    Differences processing ...............................
Zaloha AWK: Warning: 686 symbolic link(s) in <sourceDir> that are neither followed nor synchronized to <backupDir>
Zaloha2.sh: Error on line 3868

**Comment by Fitus** [comment]
Hello,

thanks for the report. I think that I have found the cause: Presumably there will be another warning that tries to write to /dev/stderr, and the first warning closes /dev/stderr, which (at least with mawk) throws an exception.

Please retry with the latest commit.

BTW: If you do not want to see the warning about symbolic links, you can use option <code>--noWarnSLinks</code>.

Let me know the outcome.

Thanks, F.

**Comment by muralikodali** [comment]
Thanks for the update.

updated version is not giving any errors.

Can you please let me know the options for,

- copying symbolic links
- excluding multiple directories

**Comment by Fitus** [comment]
Hello,

thanks for the good news. Per your questions:

Symbolic links are currently not synchronized to the backup directory. The reason is that some filesystems (e.g. FAT) do not support symbolic links and I want maximum freedom for the choice of backup media. But the symbolic links are not lost: They are contained in CSV metadata and also in restore script <code>820_restore_sym_links.sh</code>, so a restore of your (non-FAT) source directory with the symbolic links is possible.

If you are happy with this explanation, then fine. However, if you need a true synchronization of symbolic links, then please post a new dedicated issue "Enhancement Request: Synchronization of symbolic links". But it will take me some time to develop, and it will make the program (again) bigger ...

Excluding multiple directories: There is an example in the new README how to do it: Just use several <code>--findSourceOps</code> or several <code>--findGeneralOps</code>, depending on the effect you want to achieve:

```bash
--findSourceOps='( -type d -a -name .Waste ) -prune -o'         \
--findSourceOps='( -type d -a -name .Other_Waste ) -prune -o'   \
--findSourceOps='( -type d -a -name .Other_Waste2 ) -prune -o'  \
--findSourceOps='( -type d -a -name .Other_Waste3 ) -prune -o'  \
and so on
```

Regards, F.

**Comment by muralikodali** [comment]
i have found **820_restore_sym_links.sh** file in the metadir , for the backup done with zaloha.sh, but for the backups done with zaloha2.sh there are no such symlink files present in metadir.

**Comment by Fitus** [comment]
Hello,

in your case, production of the <code>820_restore_sym_links.sh</code> file is switched off by the option <code>--noRestore</code>. It has nothing to do with Zaloha.sh versus Zaloha2.sh:

Look at the Flowchart here: https://fitus.github.io/flowchart.html and step forward till step 42: You see in the description that this step can be switched off by <code>--noRestore</code>.

Even if you do not have <code>820_restore_sym_links.sh</code>, you still have the symbolic link information in file <code>505_target.csv</code>. It is a normal CSV file which you can open e.g. in LibreOffice Calc or MS Excel. Data model is described here: https://fitus.github.io/data_model.html. Symbolic links are the records where the third column has the value <code>l</code>.

If you do not have file <code>820_restore_sym_links.sh</code>, you can still produce it from file <code>505_target.csv</code> (as is described in the Documentation).

Regards, F.

**Comment by muralikodali** [comment]
Thanks for explaining about the problem in depth

removing --noRestore option produced 820_restore_sym_links.sh

Documentation is exhaustive. we should first do our home work there.

As the program is designed to sync large sizes with so many options available, **i request you to provide the option to execute the program with configuration file for general settings and profiles for each backup**. It relieves from typing lengthy commands with so many options.

**Comment by Fitus** [comment]
Hi,

a param file reading would blow the program size. Zaloha2 is already too big anyway ...

A hint for a better solution I use on my machines: Use wrapper scripts. Typically, the wrappers have more to do than just calling Zaloha2. For instance <code>Zaloha2_achilles_HDD_USB.sh</code>:

* Mount the USB stick
* Special backup of a small directory with "secrets" like passwords, private keys etc: tar, gzip, encrypt and write to USB
* Then call Zaloha2 with the required arguments to synchronize the bulk of regular data
* Unmount the USB stick

And I have desktop icons that start the various wrapper scripts. Also: I plug in the USB stick, double-click the icon, see the wrapper + Zaloha2 running, confirm the actions, wait till it finishes, unplug the USB stick. Easy.

Regards, F.
