### ISSUE TITLE
Zaloha2.sh: Error on line 3070 - when executing Simple_Demo_step1.sh

### ISSUE THREAD

**Issue by jusuchin85** [Fitus/Zaloha2.sh#3]
Hi there,

I've downloaded `Zaloha2` from the repo and attempted a test on my local Mac machine to replace `rsync` on our server later on.

I ran the `Simple_Demo_step1.sh` to generate sample data in both `test_source` and `test_backup`. Made `Zaloha2.sh` executable and attempted to run the simple sync command:

```
./Zaloha2.sh --sourceDir="test_source" --backupDir="test_backup"
```

However, I stumbled upon the following error:
```
ANALYZING ./test_source/ AND ./test_backup/
===========================================
    Parsing .............................................. done.
    exec find ./test_backup/.Zaloha_metadata/ -path ./test_backup/.Zaloha_metadata/999_mark_executed -type f -printf '///\tL\t%y\t%s\t%Ts\t%F\t%D\t%i\t%n\t%u\t%g\t%m\t0\t%P\t///' '(' -lname '*///*' -printf '\t' -o -printf '\t%l' ')' -printf '\t///\n'
find: -printf: unknown primary or operator
Zaloha2.sh: Error on line 3070
```

Before this, I tried with my own directory to rule out the sample example, but got the same error.

Is there something that I need to do prior?

Cheers! :)

**Comment by Fitus** [comment]
Hello,

thanks for your interest.

Yes, I know that some systems have FIND commands that don't support the <code>-printf</code> operator. I think that this is true for BSD systems also.

Unfortunately, Zaloha relies heavily on the <code>-printf</code> operator. It allows to obtain all required metadata from a directory in one Unics process, which yields good performance. Any workaround would presumably perform much worse.

Actually I see only one possible solution: Install GNU find on your machine and make it the default find command (= first in PATH).

Wish you a good luck, F.

**Comment by jusuchin85** [comment]
@Fitus , thanks for the tip! That actually worked like a charm (had to also install GNU `coreutils` to use the `cp` command as well).

Testing it on my end, I noticed it is faster than `rsync` (have yet to test it between two NFS mounts).

Is there a way I can schedule Zaloha to execute nightly, and perform a process that is similar to `rsync --delete` on the target directory (if the file/directory does not exist in the source directory)?

Or maybe I was looking at this the wrong way...lol

**Comment by Fitus** [comment]
Hi jusuchin85,

thanks for the good news.

Yes, you can use the <code>--noExec</code> option to let Zaloha just prepare the execution scripts but not execute them (and not ask any questions then, of course). All is described in the docu BTW, under section "Automatic operations".

From the prepared execution scripts, you can choose to execute only <code>610_exec1.sh</code> and <code>640_exec4.sh</code> to emulate a kind of "delete only" regime, if this is what you want to achieve (sorry I am not an rsync expert).

Regards, F.
