### ISSUE TITLE
possible to copy/sync xattr

### ISSUE THREAD

**Issue by spamwax** [Fitus/Zaloha2.sh#4]
Is it possible to sync/copy xattr of files by providing some sort of flag? (similar to `rsync --xattr`)

**Comment by Fitus** [comment]
Hello,

extended attributes have not been a topic so far.

What I could do for you: add new option <b>--cpOptions</b>.

(there has already been a related interest in the past)

This option would make it possible to specify different cp command line options, e.g.:

<b>--cpOptions='--preserve=timestamps,xattr'</b>

This should preserve the extended attributes during copying (according to the cp manpage). Also a solution for the Local Mode.

Detection of changes of extended attributes is out of scope, however, unless such changes are detectable via file modification times.

Let me know.

F.

**Comment by spamwax** [comment]
Yes, that would work for my use case.

**Comment by Fitus** [comment]
Hi, your Enhancement Request is there. F.

**Comment by spamwax** [comment]
Thanks for implementing this 👍
